version: '3.8'

services:

  bank-api:
    build:
        context: ./assignment-bank-api/
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
    environment:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: rb_db
        DB_USER: rb_database_user
        DB_PASSWORD: 123#$%abc%$#ABC
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: 123#$%abc%$#ABC
      POSTGRES_USER: rb_database_user
      POSTGRES_DB: rb_db
    ports:
      - "5432:5432"